//go:build ignore

// Generate the reviewed amd64 table explicitly; never run during a build.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) > 1 && os.Args[1] == "--" {
		os.Args = append(os.Args[:1], os.Args[2:]...)
	}
	if len(os.Args) != 3 {
		panic("usage: gen-syscall-table <zsysnum_linux_amd64.go> <output>")
	}
	source, err := os.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	actions, reasons := map[string]string{}, map[string]string{}
	group := func(action, why, names string) {
		for _, n := range strings.Fields(names) {
			if _, ok := actions[n]; ok {
				panic("duplicate policy: " + n)
			}
			actions[n], reasons[n] = action, why
		}
	}
	group("deny", "mount", "mount umount2 pivot_root open_tree move_mount fsopen fsmount fspick mount_setattr fsconfig open_tree_attr")
	group("deny", "process-reach", "ptrace process_vm_readv process_vm_writev pidfd_getfd process_mrelease")
	group("deny", "kernel-surface", "bpf perf_event_open userfaultfd keyctl add_key request_key io_uring_setup io_uring_enter io_uring_register kexec_load kexec_file_load init_module finit_module delete_module reboot swapon swapoff settimeofday clock_settime clock_adjtime adjtimex")
	group("deny", "personality", "personality")
	group("deny", "handles", "open_by_handle_at")
	group("deny", "namespaces", "setns")
	group("deny", "servers", "listen")
	group("deny", "metadata", "chmod fchmod fchmodat fchmodat2 chown lchown fchown fchownat setxattr lsetxattr fsetxattr setxattrat removexattr lremovexattr fremovexattr removexattrat utime utimes futimesat utimensat file_setattr")
	group("deny", "mqueue", "mq_open mq_unlink mq_timedsend mq_timedreceive mq_notify mq_getsetattr")
	group("deny", "filesystem-sync", "sync syncfs")
	group("enosys", "unimplemented", "uselib _sysctl create_module get_kernel_syms query_module nfsservctl getpmsg putpmsg afs_syscall tuxcall security lookup_dcookie epoll_ctl_old epoll_wait_old vserver")
	group("enosys", "legacy-clone-fallback", "clone3")
	for _, n := range strings.Fields("clone unshare socket socketpair ioctl fcntl flock setrlimit prlimit64 kill tkill tgkill rt_sigqueueinfo rt_tgsigqueueinfo pidfd_send_signal setpriority ioprio_set sched_setparam sched_setscheduler sched_setaffinity sched_setattr migrate_pages move_pages") {
		group("filter:"+n, "arguments", n)
	}
	group("allow", "fs-read", "read open close stat fstat lstat poll lseek pread64 readv access pipe select getdents getcwd readlink statfs fstatfs readahead getxattr lgetxattr fgetxattr listxattr llistxattr flistxattr getdents64 openat newfstatat readlinkat faccessat pselect6 ppoll dup dup2 dup3 pipe2 preadv preadv2 openat2 faccessat2 close_range name_to_handle_at statx statmount listmount file_getattr getxattrat listxattrat fsync fdatasync")
	group("allow", "fs-mutate", "write pwrite64 writev truncate ftruncate rename mkdir rmdir creat link unlink symlink mknod mkdirat mknodat unlinkat renameat linkat symlinkat splice tee vmsplice fallocate pwritev pwritev2 renameat2 copy_file_range sendfile sync_file_range")
	group("allow", "proc-other", "pidfd_open process_madvise kcmp")
	group("allow", "ipc", "shmget shmat shmctl shmdt semget semop semctl semtimedop msgget msgsnd msgrcv msgctl")
	group("allow", "net-io", "connect accept accept4 bind sendto sendmsg sendmmsg recvfrom recvmsg recvmmsg shutdown getsockopt setsockopt getsockname getpeername")
	group("allow", "cred", "setuid setgid setreuid setregid setresuid setresgid setfsuid setfsgid setgroups capset")
	group("allow", "cap-gated-init", "acct quotactl quotactl_fd syslog sethostname setdomainname iopl ioperm vhangup chroot")
	group("allow", "sandbox", "seccomp landlock_create_ruleset landlock_add_rule landlock_restrict_self prctl")
	var out bytes.Buffer
	out.WriteString("//go:build linux\n\n// Code generated by scripts/gen-syscall-table.go; reviewed policy. DO NOT EDIT.\npackage confine\n\ntype sysRow struct { nr uint32; name, action, why string }\n\nvar syscallTable = []sysRow{\n")
	seen := map[string]bool{}
	counts := map[string]int{}
	for _, m := range regexp.MustCompile(`(?m)^\s*SYS_([A-Z0-9_]+)\s*=\s*(\d+)\s*$`).FindAllSubmatch(source, -1) {
		name := strings.ToLower(string(m[1]))
		nr, _ := strconv.Atoi(string(m[2]))
		action, why := actions[name], reasons[name]
		if action == "" {
			action, why = "allow", "self"
		}
		seen[name] = true
		counts[strings.Split(action, ":")[0]]++
		fmt.Fprintf(&out, "{%d, %q, %q, %q},\n", nr, strings.ToUpper(name), action, why)
	}
	for n := range actions {
		if !seen[n] {
			panic("not in amd64 syscall table: " + n)
		}
	}
	if counts["allow"] != 276 || counts["deny"] != 70 || counts["enosys"] != 16 || counts["filter"] != 23 {
		panic(fmt.Sprint(counts))
	}
	out.WriteString("}\n")
	data, err := format.Source(out.Bytes())
	if err != nil {
		panic(err)
	}
	if err = os.WriteFile(os.Args[2], data, 0644); err != nil {
		panic(err)
	}
	fmt.Println(counts)
}
