package confine

// Pending cases owned by migration lane M3. Remove each entry when migrated.
var pendingM3 = map[string]string{
	"L-INJECT-ERRNO":              "existing unregistered leg outside this lane; pending proof migration",
	"L-FAULT-fds-ENOSYS":          "existing unregistered leg outside this lane; pending proof migration",
	"L-MOUNT-STAGES":              "existing unregistered leg outside this lane; pending proof migration",
	"L-DEVICES":                   "existing unregistered leg outside this lane; pending proof migration",
	"L-TTY-NODEV":                 "existing unregistered leg outside this lane; pending proof migration",
	"L-SCRATCH":                   "existing unregistered leg outside this lane; pending proof migration",
	"L-TMP-VISIBLE":               "existing unregistered leg outside this lane; pending proof migration",
	"L-PS-VISIBLE":                "existing unregistered leg outside this lane; pending proof migration",
	"U-SpecRejectsUnknownProfile": "existing unregistered leg outside this lane; pending proof migration",
	"L-FAULT-caps":                "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-cmdread":             "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-cwd":                 "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-exec":                "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-fds":                 "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-landlock":            "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-mounts":              "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-nnp":                 "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-nsverify":            "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-rlimits":             "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-seccomp":             "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-selfcheck":           "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-session":             "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-spec":                "legacy registered leg; migration lane owns its proof conversion",
	"L-FAULT-tsync":               "legacy registered leg; migration lane owns its proof conversion",
	"L-FIFO-WRITE":                "legacy registered leg; migration lane owns its proof conversion",
	"L-FILEATTR-ERRNO":            "legacy registered leg; migration lane owns its proof conversion",
	"L-HOSTMOUNTS-UNCHANGED":      "legacy registered leg; migration lane owns its proof conversion",
	"L-LL-REQUIRED":               "legacy registered leg; migration lane owns its proof conversion",
	"L-META-EROFS":                "legacy registered leg; migration lane owns its proof conversion",
	"L-META-ROOT":                 "legacy registered leg; migration lane owns its proof conversion",
	"L-META-SUBMOUNT":             "legacy registered leg; migration lane owns its proof conversion",
	"L-MQUEUE":                    "legacy registered leg; migration lane owns its proof conversion",
	"L-MQUEUE-ERRNO":              "legacy registered leg; migration lane owns its proof conversion",
	"L-NNP-LANDLOCK":              "legacy registered leg; migration lane owns its proof conversion",
	"L-NSVERIFY":                  "legacy registered leg; migration lane owns its proof conversion",
	"L-NSVERIFY-ipc":              "legacy registered leg; migration lane owns its proof conversion",
	"L-NSVERIFY-mnt":              "legacy registered leg; migration lane owns its proof conversion",
	"L-NSVERIFY-pid":              "legacy registered leg; migration lane owns its proof conversion",
	"L-NSVERIFY-user":             "legacy registered leg; migration lane owns its proof conversion",
	"L-ROOT-NPROC":                "legacy registered leg; migration lane owns its proof conversion",
	"L-ROOT-PROC":                 "legacy registered leg; migration lane owns its proof conversion",
	"L-ROOT-STATE":                "legacy registered leg; migration lane owns its proof conversion",
	"L-SCRATCH-META":              "legacy registered leg; migration lane owns its proof conversion",
	"L-SELFCHECK-CREDS":           "legacy registered leg; migration lane owns its proof conversion",
	"L-SELFCHECK-LL":              "legacy registered leg; migration lane owns its proof conversion",
	"L-SETUID":                    "legacy registered leg; migration lane owns its proof conversion",
	"L-SPEC-REJECT":               "legacy registered leg; migration lane owns its proof conversion",
	"L-WRITE-ERRNO":               "legacy registered leg; migration lane owns its proof conversion",
	"L-WRITE-ROOT":                "legacy registered leg; migration lane owns its proof conversion",
	"L-WRITE-SUBMOUNT":            "legacy registered leg; migration lane owns its proof conversion",
	"U-StatusProtocol":            "legacy registered leg; migration lane owns its proof conversion",
}
