//go:build linux

package confine

import "testing"

func TestSyscallRowDecisions(t *testing.T) {
	for _, abi := range []string{"native", "abi1"} {
		t.Run(abi, func(t *testing.T) {
			t.Run("U-SC-MOUNT", func(t *testing.T) {
				p := newProof(t, "U-SC-MOUNT")
				checkSyscallRow(t, "MOUNT", 165, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-UMOUNT2", func(t *testing.T) {
				p := newProof(t, "U-SC-UMOUNT2")
				checkSyscallRow(t, "UMOUNT2", 166, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PIVOT_ROOT", func(t *testing.T) {
				p := newProof(t, "U-SC-PIVOT_ROOT")
				checkSyscallRow(t, "PIVOT_ROOT", 155, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-OPEN_TREE", func(t *testing.T) {
				p := newProof(t, "U-SC-OPEN_TREE")
				checkSyscallRow(t, "OPEN_TREE", 428, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-MOVE_MOUNT", func(t *testing.T) {
				p := newProof(t, "U-SC-MOVE_MOUNT")
				checkSyscallRow(t, "MOVE_MOUNT", 429, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FSOPEN", func(t *testing.T) {
				p := newProof(t, "U-SC-FSOPEN")
				checkSyscallRow(t, "FSOPEN", 430, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FSMOUNT", func(t *testing.T) {
				p := newProof(t, "U-SC-FSMOUNT")
				checkSyscallRow(t, "FSMOUNT", 432, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FSPICK", func(t *testing.T) {
				p := newProof(t, "U-SC-FSPICK")
				checkSyscallRow(t, "FSPICK", 433, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-MOUNT_SETATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-MOUNT_SETATTR")
				checkSyscallRow(t, "MOUNT_SETATTR", 442, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FSCONFIG", func(t *testing.T) {
				p := newProof(t, "U-SC-FSCONFIG")
				checkSyscallRow(t, "FSCONFIG", 431, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-OPEN_TREE_ATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-OPEN_TREE_ATTR")
				checkSyscallRow(t, "OPEN_TREE_ATTR", 467, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PTRACE", func(t *testing.T) {
				p := newProof(t, "U-SC-PTRACE")
				checkSyscallRow(t, "PTRACE", 101, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PROCESS_VM_READV", func(t *testing.T) {
				p := newProof(t, "U-SC-PROCESS_VM_READV")
				checkSyscallRow(t, "PROCESS_VM_READV", 310, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PROCESS_VM_WRITEV", func(t *testing.T) {
				p := newProof(t, "U-SC-PROCESS_VM_WRITEV")
				checkSyscallRow(t, "PROCESS_VM_WRITEV", 311, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PIDFD_GETFD", func(t *testing.T) {
				p := newProof(t, "U-SC-PIDFD_GETFD")
				checkSyscallRow(t, "PIDFD_GETFD", 438, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-BPF", func(t *testing.T) {
				p := newProof(t, "U-SC-BPF")
				checkSyscallRow(t, "BPF", 321, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PERF_EVENT_OPEN", func(t *testing.T) {
				p := newProof(t, "U-SC-PERF_EVENT_OPEN")
				checkSyscallRow(t, "PERF_EVENT_OPEN", 298, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-USERFAULTFD", func(t *testing.T) {
				p := newProof(t, "U-SC-USERFAULTFD")
				checkSyscallRow(t, "USERFAULTFD", 323, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-KEYCTL", func(t *testing.T) {
				p := newProof(t, "U-SC-KEYCTL")
				checkSyscallRow(t, "KEYCTL", 250, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-ADD_KEY", func(t *testing.T) {
				p := newProof(t, "U-SC-ADD_KEY")
				checkSyscallRow(t, "ADD_KEY", 248, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-REQUEST_KEY", func(t *testing.T) {
				p := newProof(t, "U-SC-REQUEST_KEY")
				checkSyscallRow(t, "REQUEST_KEY", 249, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-IO_URING_SETUP", func(t *testing.T) {
				p := newProof(t, "U-SC-IO_URING_SETUP")
				checkSyscallRow(t, "IO_URING_SETUP", 425, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-IO_URING_ENTER", func(t *testing.T) {
				p := newProof(t, "U-SC-IO_URING_ENTER")
				checkSyscallRow(t, "IO_URING_ENTER", 426, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-IO_URING_REGISTER", func(t *testing.T) {
				p := newProof(t, "U-SC-IO_URING_REGISTER")
				checkSyscallRow(t, "IO_URING_REGISTER", 427, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-KEXEC_LOAD", func(t *testing.T) {
				p := newProof(t, "U-SC-KEXEC_LOAD")
				checkSyscallRow(t, "KEXEC_LOAD", 246, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-KEXEC_FILE_LOAD", func(t *testing.T) {
				p := newProof(t, "U-SC-KEXEC_FILE_LOAD")
				checkSyscallRow(t, "KEXEC_FILE_LOAD", 320, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-INIT_MODULE", func(t *testing.T) {
				p := newProof(t, "U-SC-INIT_MODULE")
				checkSyscallRow(t, "INIT_MODULE", 175, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FINIT_MODULE", func(t *testing.T) {
				p := newProof(t, "U-SC-FINIT_MODULE")
				checkSyscallRow(t, "FINIT_MODULE", 313, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-DELETE_MODULE", func(t *testing.T) {
				p := newProof(t, "U-SC-DELETE_MODULE")
				checkSyscallRow(t, "DELETE_MODULE", 176, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-REBOOT", func(t *testing.T) {
				p := newProof(t, "U-SC-REBOOT")
				checkSyscallRow(t, "REBOOT", 169, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SWAPON", func(t *testing.T) {
				p := newProof(t, "U-SC-SWAPON")
				checkSyscallRow(t, "SWAPON", 167, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SWAPOFF", func(t *testing.T) {
				p := newProof(t, "U-SC-SWAPOFF")
				checkSyscallRow(t, "SWAPOFF", 168, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SETTIMEOFDAY", func(t *testing.T) {
				p := newProof(t, "U-SC-SETTIMEOFDAY")
				checkSyscallRow(t, "SETTIMEOFDAY", 164, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-CLOCK_SETTIME", func(t *testing.T) {
				p := newProof(t, "U-SC-CLOCK_SETTIME")
				checkSyscallRow(t, "CLOCK_SETTIME", 227, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-CLOCK_ADJTIME", func(t *testing.T) {
				p := newProof(t, "U-SC-CLOCK_ADJTIME")
				checkSyscallRow(t, "CLOCK_ADJTIME", 305, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-ADJTIMEX", func(t *testing.T) {
				p := newProof(t, "U-SC-ADJTIMEX")
				checkSyscallRow(t, "ADJTIMEX", 159, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PERSONALITY", func(t *testing.T) {
				p := newProof(t, "U-SC-PERSONALITY")
				checkSyscallRow(t, "PERSONALITY", 135, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-OPEN_BY_HANDLE_AT", func(t *testing.T) {
				p := newProof(t, "U-SC-OPEN_BY_HANDLE_AT")
				checkSyscallRow(t, "OPEN_BY_HANDLE_AT", 304, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SETNS", func(t *testing.T) {
				p := newProof(t, "U-SC-SETNS")
				checkSyscallRow(t, "SETNS", 308, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-LISTEN", func(t *testing.T) {
				p := newProof(t, "U-SC-LISTEN")
				checkSyscallRow(t, "LISTEN", 50, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-CHMOD", func(t *testing.T) {
				p := newProof(t, "U-SC-CHMOD")
				checkSyscallRow(t, "CHMOD", 90, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FCHMOD", func(t *testing.T) {
				p := newProof(t, "U-SC-FCHMOD")
				checkSyscallRow(t, "FCHMOD", 91, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FCHMODAT", func(t *testing.T) {
				p := newProof(t, "U-SC-FCHMODAT")
				checkSyscallRow(t, "FCHMODAT", 268, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FCHMODAT2", func(t *testing.T) {
				p := newProof(t, "U-SC-FCHMODAT2")
				checkSyscallRow(t, "FCHMODAT2", 452, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-CHOWN", func(t *testing.T) {
				p := newProof(t, "U-SC-CHOWN")
				checkSyscallRow(t, "CHOWN", 92, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-LCHOWN", func(t *testing.T) {
				p := newProof(t, "U-SC-LCHOWN")
				checkSyscallRow(t, "LCHOWN", 94, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FCHOWN", func(t *testing.T) {
				p := newProof(t, "U-SC-FCHOWN")
				checkSyscallRow(t, "FCHOWN", 93, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FCHOWNAT", func(t *testing.T) {
				p := newProof(t, "U-SC-FCHOWNAT")
				checkSyscallRow(t, "FCHOWNAT", 260, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SETXATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-SETXATTR")
				checkSyscallRow(t, "SETXATTR", 188, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-LSETXATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-LSETXATTR")
				checkSyscallRow(t, "LSETXATTR", 189, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FSETXATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-FSETXATTR")
				checkSyscallRow(t, "FSETXATTR", 190, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SETXATTRAT", func(t *testing.T) {
				p := newProof(t, "U-SC-SETXATTRAT")
				checkSyscallRow(t, "SETXATTRAT", 463, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-REMOVEXATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-REMOVEXATTR")
				checkSyscallRow(t, "REMOVEXATTR", 197, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-LREMOVEXATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-LREMOVEXATTR")
				checkSyscallRow(t, "LREMOVEXATTR", 198, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FREMOVEXATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-FREMOVEXATTR")
				checkSyscallRow(t, "FREMOVEXATTR", 199, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-REMOVEXATTRAT", func(t *testing.T) {
				p := newProof(t, "U-SC-REMOVEXATTRAT")
				checkSyscallRow(t, "REMOVEXATTRAT", 466, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-UTIME", func(t *testing.T) {
				p := newProof(t, "U-SC-UTIME")
				checkSyscallRow(t, "UTIME", 132, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-UTIMES", func(t *testing.T) {
				p := newProof(t, "U-SC-UTIMES")
				checkSyscallRow(t, "UTIMES", 235, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FUTIMESAT", func(t *testing.T) {
				p := newProof(t, "U-SC-FUTIMESAT")
				checkSyscallRow(t, "FUTIMESAT", 261, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-UTIMENSAT", func(t *testing.T) {
				p := newProof(t, "U-SC-UTIMENSAT")
				checkSyscallRow(t, "UTIMENSAT", 280, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FILE_SETATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-FILE_SETATTR")
				checkSyscallRow(t, "FILE_SETATTR", 469, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-MQ_OPEN", func(t *testing.T) {
				p := newProof(t, "U-SC-MQ_OPEN")
				checkSyscallRow(t, "MQ_OPEN", 240, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-MQ_UNLINK", func(t *testing.T) {
				p := newProof(t, "U-SC-MQ_UNLINK")
				checkSyscallRow(t, "MQ_UNLINK", 241, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-MQ_TIMEDSEND", func(t *testing.T) {
				p := newProof(t, "U-SC-MQ_TIMEDSEND")
				checkSyscallRow(t, "MQ_TIMEDSEND", 242, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-MQ_TIMEDRECEIVE", func(t *testing.T) {
				p := newProof(t, "U-SC-MQ_TIMEDRECEIVE")
				checkSyscallRow(t, "MQ_TIMEDRECEIVE", 243, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-MQ_NOTIFY", func(t *testing.T) {
				p := newProof(t, "U-SC-MQ_NOTIFY")
				checkSyscallRow(t, "MQ_NOTIFY", 244, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-MQ_GETSETATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-MQ_GETSETATTR")
				checkSyscallRow(t, "MQ_GETSETATTR", 245, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SYNC", func(t *testing.T) {
				p := newProof(t, "U-SC-SYNC")
				checkSyscallRow(t, "SYNC", 162, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SYNCFS", func(t *testing.T) {
				p := newProof(t, "U-SC-SYNCFS")
				checkSyscallRow(t, "SYNCFS", 306, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-CLONE3", func(t *testing.T) {
				p := newProof(t, "U-SC-CLONE3")
				checkSyscallRow(t, "CLONE3", 435, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-USELIB", func(t *testing.T) {
				p := newProof(t, "U-SC-USELIB")
				checkSyscallRow(t, "USELIB", 134, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-_SYSCTL", func(t *testing.T) {
				p := newProof(t, "U-SC-_SYSCTL")
				checkSyscallRow(t, "_SYSCTL", 156, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-CREATE_MODULE", func(t *testing.T) {
				p := newProof(t, "U-SC-CREATE_MODULE")
				checkSyscallRow(t, "CREATE_MODULE", 174, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-GET_KERNEL_SYMS", func(t *testing.T) {
				p := newProof(t, "U-SC-GET_KERNEL_SYMS")
				checkSyscallRow(t, "GET_KERNEL_SYMS", 177, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-QUERY_MODULE", func(t *testing.T) {
				p := newProof(t, "U-SC-QUERY_MODULE")
				checkSyscallRow(t, "QUERY_MODULE", 178, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-NFSSERVCTL", func(t *testing.T) {
				p := newProof(t, "U-SC-NFSSERVCTL")
				checkSyscallRow(t, "NFSSERVCTL", 180, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-GETPMSG", func(t *testing.T) {
				p := newProof(t, "U-SC-GETPMSG")
				checkSyscallRow(t, "GETPMSG", 181, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PUTPMSG", func(t *testing.T) {
				p := newProof(t, "U-SC-PUTPMSG")
				checkSyscallRow(t, "PUTPMSG", 182, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-AFS_SYSCALL", func(t *testing.T) {
				p := newProof(t, "U-SC-AFS_SYSCALL")
				checkSyscallRow(t, "AFS_SYSCALL", 183, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-TUXCALL", func(t *testing.T) {
				p := newProof(t, "U-SC-TUXCALL")
				checkSyscallRow(t, "TUXCALL", 184, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SECURITY", func(t *testing.T) {
				p := newProof(t, "U-SC-SECURITY")
				checkSyscallRow(t, "SECURITY", 185, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-LOOKUP_DCOOKIE", func(t *testing.T) {
				p := newProof(t, "U-SC-LOOKUP_DCOOKIE")
				checkSyscallRow(t, "LOOKUP_DCOOKIE", 212, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-EPOLL_CTL_OLD", func(t *testing.T) {
				p := newProof(t, "U-SC-EPOLL_CTL_OLD")
				checkSyscallRow(t, "EPOLL_CTL_OLD", 214, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-EPOLL_WAIT_OLD", func(t *testing.T) {
				p := newProof(t, "U-SC-EPOLL_WAIT_OLD")
				checkSyscallRow(t, "EPOLL_WAIT_OLD", 215, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-VSERVER", func(t *testing.T) {
				p := newProof(t, "U-SC-VSERVER")
				checkSyscallRow(t, "VSERVER", 236, actEnosys)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-CLONE", func(t *testing.T) {
				p := newProof(t, "U-SC-CLONE")
				checkSyscallRow(t, "CLONE", 56, actDeny, 0x10000000)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-UNSHARE", func(t *testing.T) {
				p := newProof(t, "U-SC-UNSHARE")
				checkSyscallRow(t, "UNSHARE", 272, actDeny, 0x10000000)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SOCKET", func(t *testing.T) {
				p := newProof(t, "U-SC-SOCKET")
				checkSyscallRow(t, "SOCKET", 41, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SOCKETPAIR", func(t *testing.T) {
				p := newProof(t, "U-SC-SOCKETPAIR")
				checkSyscallRow(t, "SOCKETPAIR", 53, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-IOCTL", func(t *testing.T) {
				p := newProof(t, "U-SC-IOCTL")
				checkSyscallRow(t, "IOCTL", 16, actDeny, 0, 0x5412)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FCNTL", func(t *testing.T) {
				p := newProof(t, "U-SC-FCNTL")
				checkSyscallRow(t, "FCNTL", 72, actDeny, 0, 1031)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-FLOCK", func(t *testing.T) {
				p := newProof(t, "U-SC-FLOCK")
				checkSyscallRow(t, "FLOCK", 73, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SETRLIMIT", func(t *testing.T) {
				p := newProof(t, "U-SC-SETRLIMIT")
				checkSyscallRow(t, "SETRLIMIT", 160, actDeny, 4, 1)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PRLIMIT64", func(t *testing.T) {
				p := newProof(t, "U-SC-PRLIMIT64")
				checkSyscallRow(t, "PRLIMIT64", 302, actDeny, 0, 4, 1)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PROCESS_MRELEASE", func(t *testing.T) {
				p := newProof(t, "U-SC-PROCESS_MRELEASE")
				checkSyscallRow(t, "PROCESS_MRELEASE", 448, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-KILL", func(t *testing.T) {
				p := newProof(t, "U-SC-KILL")
				checkSyscallRow(t, "KILL", 62, actDeny, 1, 15)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-TKILL", func(t *testing.T) {
				p := newProof(t, "U-SC-TKILL")
				checkSyscallRow(t, "TKILL", 200, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-TGKILL", func(t *testing.T) {
				p := newProof(t, "U-SC-TGKILL")
				checkSyscallRow(t, "TGKILL", 234, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-RT_SIGQUEUEINFO", func(t *testing.T) {
				p := newProof(t, "U-SC-RT_SIGQUEUEINFO")
				checkSyscallRow(t, "RT_SIGQUEUEINFO", 129, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-RT_TGSIGQUEUEINFO", func(t *testing.T) {
				p := newProof(t, "U-SC-RT_TGSIGQUEUEINFO")
				checkSyscallRow(t, "RT_TGSIGQUEUEINFO", 297, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-PIDFD_SEND_SIGNAL", func(t *testing.T) {
				p := newProof(t, "U-SC-PIDFD_SEND_SIGNAL")
				checkSyscallRow(t, "PIDFD_SEND_SIGNAL", 424, actDeny)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SETPRIORITY", func(t *testing.T) {
				p := newProof(t, "U-SC-SETPRIORITY")
				checkSyscallRow(t, "SETPRIORITY", 141, actDeny, 2, 0)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-IOPRIO_SET", func(t *testing.T) {
				p := newProof(t, "U-SC-IOPRIO_SET")
				checkSyscallRow(t, "IOPRIO_SET", 251, actDeny, 3, 0)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SCHED_SETPARAM", func(t *testing.T) {
				p := newProof(t, "U-SC-SCHED_SETPARAM")
				checkSyscallRow(t, "SCHED_SETPARAM", 142, actDeny, 1)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SCHED_SETSCHEDULER", func(t *testing.T) {
				p := newProof(t, "U-SC-SCHED_SETSCHEDULER")
				checkSyscallRow(t, "SCHED_SETSCHEDULER", 144, actDeny, 1)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SCHED_SETAFFINITY", func(t *testing.T) {
				p := newProof(t, "U-SC-SCHED_SETAFFINITY")
				checkSyscallRow(t, "SCHED_SETAFFINITY", 203, actDeny, 1)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-SCHED_SETATTR", func(t *testing.T) {
				p := newProof(t, "U-SC-SCHED_SETATTR")
				checkSyscallRow(t, "SCHED_SETATTR", 314, actDeny, 1)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-MIGRATE_PAGES", func(t *testing.T) {
				p := newProof(t, "U-SC-MIGRATE_PAGES")
				checkSyscallRow(t, "MIGRATE_PAGES", 256, actDeny, 1)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
			t.Run("U-SC-MOVE_PAGES", func(t *testing.T) {
				p := newProof(t, "U-SC-MOVE_PAGES")
				checkSyscallRow(t, "MOVE_PAGES", 279, actDeny, 1)
				p.Control("decision", ControlResult{Valid: !t.Failed(), Detail: "independent syscall number, arguments and action evaluated"})
				p.Finish()
			})
		})
	}
}
