//go:build linux

package confine

import "testing"

func TestSyscallRowDecisions(t *testing.T) {
	t.Run("U-SC-MOUNT", func(t *testing.T) { checkSyscallRow(t, "MOUNT", 165, actDeny) })
	t.Run("U-SC-UMOUNT2", func(t *testing.T) { checkSyscallRow(t, "UMOUNT2", 166, actDeny) })
	t.Run("U-SC-PIVOT_ROOT", func(t *testing.T) { checkSyscallRow(t, "PIVOT_ROOT", 155, actDeny) })
	t.Run("U-SC-OPEN_TREE", func(t *testing.T) { checkSyscallRow(t, "OPEN_TREE", 428, actDeny) })
	t.Run("U-SC-MOVE_MOUNT", func(t *testing.T) { checkSyscallRow(t, "MOVE_MOUNT", 429, actDeny) })
	t.Run("U-SC-FSOPEN", func(t *testing.T) { checkSyscallRow(t, "FSOPEN", 430, actDeny) })
	t.Run("U-SC-FSMOUNT", func(t *testing.T) { checkSyscallRow(t, "FSMOUNT", 432, actDeny) })
	t.Run("U-SC-FSPICK", func(t *testing.T) { checkSyscallRow(t, "FSPICK", 433, actDeny) })
	t.Run("U-SC-MOUNT_SETATTR", func(t *testing.T) { checkSyscallRow(t, "MOUNT_SETATTR", 442, actDeny) })
	t.Run("U-SC-FSCONFIG", func(t *testing.T) { checkSyscallRow(t, "FSCONFIG", 431, actDeny) })
	t.Run("U-SC-OPEN_TREE_ATTR", func(t *testing.T) { checkSyscallRow(t, "OPEN_TREE_ATTR", 467, actDeny) })
	t.Run("U-SC-PTRACE", func(t *testing.T) { checkSyscallRow(t, "PTRACE", 101, actDeny) })
	t.Run("U-SC-PROCESS_VM_READV", func(t *testing.T) { checkSyscallRow(t, "PROCESS_VM_READV", 310, actDeny) })
	t.Run("U-SC-PROCESS_VM_WRITEV", func(t *testing.T) { checkSyscallRow(t, "PROCESS_VM_WRITEV", 311, actDeny) })
	t.Run("U-SC-PIDFD_GETFD", func(t *testing.T) { checkSyscallRow(t, "PIDFD_GETFD", 438, actDeny) })
	t.Run("U-SC-BPF", func(t *testing.T) { checkSyscallRow(t, "BPF", 321, actDeny) })
	t.Run("U-SC-PERF_EVENT_OPEN", func(t *testing.T) { checkSyscallRow(t, "PERF_EVENT_OPEN", 298, actDeny) })
	t.Run("U-SC-USERFAULTFD", func(t *testing.T) { checkSyscallRow(t, "USERFAULTFD", 323, actDeny) })
	t.Run("U-SC-KEYCTL", func(t *testing.T) { checkSyscallRow(t, "KEYCTL", 250, actDeny) })
	t.Run("U-SC-ADD_KEY", func(t *testing.T) { checkSyscallRow(t, "ADD_KEY", 248, actDeny) })
	t.Run("U-SC-REQUEST_KEY", func(t *testing.T) { checkSyscallRow(t, "REQUEST_KEY", 249, actDeny) })
	t.Run("U-SC-IO_URING_SETUP", func(t *testing.T) { checkSyscallRow(t, "IO_URING_SETUP", 425, actDeny) })
	t.Run("U-SC-IO_URING_ENTER", func(t *testing.T) { checkSyscallRow(t, "IO_URING_ENTER", 426, actDeny) })
	t.Run("U-SC-IO_URING_REGISTER", func(t *testing.T) { checkSyscallRow(t, "IO_URING_REGISTER", 427, actDeny) })
	t.Run("U-SC-KEXEC_LOAD", func(t *testing.T) { checkSyscallRow(t, "KEXEC_LOAD", 246, actDeny) })
	t.Run("U-SC-KEXEC_FILE_LOAD", func(t *testing.T) { checkSyscallRow(t, "KEXEC_FILE_LOAD", 320, actDeny) })
	t.Run("U-SC-INIT_MODULE", func(t *testing.T) { checkSyscallRow(t, "INIT_MODULE", 175, actDeny) })
	t.Run("U-SC-FINIT_MODULE", func(t *testing.T) { checkSyscallRow(t, "FINIT_MODULE", 313, actDeny) })
	t.Run("U-SC-DELETE_MODULE", func(t *testing.T) { checkSyscallRow(t, "DELETE_MODULE", 176, actDeny) })
	t.Run("U-SC-REBOOT", func(t *testing.T) { checkSyscallRow(t, "REBOOT", 169, actDeny) })
	t.Run("U-SC-SWAPON", func(t *testing.T) { checkSyscallRow(t, "SWAPON", 167, actDeny) })
	t.Run("U-SC-SWAPOFF", func(t *testing.T) { checkSyscallRow(t, "SWAPOFF", 168, actDeny) })
	t.Run("U-SC-SETTIMEOFDAY", func(t *testing.T) { checkSyscallRow(t, "SETTIMEOFDAY", 164, actDeny) })
	t.Run("U-SC-CLOCK_SETTIME", func(t *testing.T) { checkSyscallRow(t, "CLOCK_SETTIME", 227, actDeny) })
	t.Run("U-SC-CLOCK_ADJTIME", func(t *testing.T) { checkSyscallRow(t, "CLOCK_ADJTIME", 305, actDeny) })
	t.Run("U-SC-ADJTIMEX", func(t *testing.T) { checkSyscallRow(t, "ADJTIMEX", 159, actDeny) })
	t.Run("U-SC-PERSONALITY", func(t *testing.T) { checkSyscallRow(t, "PERSONALITY", 135, actDeny) })
	t.Run("U-SC-OPEN_BY_HANDLE_AT", func(t *testing.T) { checkSyscallRow(t, "OPEN_BY_HANDLE_AT", 304, actDeny) })
	t.Run("U-SC-SETNS", func(t *testing.T) { checkSyscallRow(t, "SETNS", 308, actDeny) })
	t.Run("U-SC-LISTEN", func(t *testing.T) { checkSyscallRow(t, "LISTEN", 50, actDeny) })
	t.Run("U-SC-CHMOD", func(t *testing.T) { checkSyscallRow(t, "CHMOD", 90, actDeny) })
	t.Run("U-SC-FCHMOD", func(t *testing.T) { checkSyscallRow(t, "FCHMOD", 91, actDeny) })
	t.Run("U-SC-FCHMODAT", func(t *testing.T) { checkSyscallRow(t, "FCHMODAT", 268, actDeny) })
	t.Run("U-SC-FCHMODAT2", func(t *testing.T) { checkSyscallRow(t, "FCHMODAT2", 452, actDeny) })
	t.Run("U-SC-CHOWN", func(t *testing.T) { checkSyscallRow(t, "CHOWN", 92, actDeny) })
	t.Run("U-SC-LCHOWN", func(t *testing.T) { checkSyscallRow(t, "LCHOWN", 94, actDeny) })
	t.Run("U-SC-FCHOWN", func(t *testing.T) { checkSyscallRow(t, "FCHOWN", 93, actDeny) })
	t.Run("U-SC-FCHOWNAT", func(t *testing.T) { checkSyscallRow(t, "FCHOWNAT", 260, actDeny) })
	t.Run("U-SC-SETXATTR", func(t *testing.T) { checkSyscallRow(t, "SETXATTR", 188, actDeny) })
	t.Run("U-SC-LSETXATTR", func(t *testing.T) { checkSyscallRow(t, "LSETXATTR", 189, actDeny) })
	t.Run("U-SC-FSETXATTR", func(t *testing.T) { checkSyscallRow(t, "FSETXATTR", 190, actDeny) })
	t.Run("U-SC-SETXATTRAT", func(t *testing.T) { checkSyscallRow(t, "SETXATTRAT", 463, actDeny) })
	t.Run("U-SC-REMOVEXATTR", func(t *testing.T) { checkSyscallRow(t, "REMOVEXATTR", 197, actDeny) })
	t.Run("U-SC-LREMOVEXATTR", func(t *testing.T) { checkSyscallRow(t, "LREMOVEXATTR", 198, actDeny) })
	t.Run("U-SC-FREMOVEXATTR", func(t *testing.T) { checkSyscallRow(t, "FREMOVEXATTR", 199, actDeny) })
	t.Run("U-SC-REMOVEXATTRAT", func(t *testing.T) { checkSyscallRow(t, "REMOVEXATTRAT", 466, actDeny) })
	t.Run("U-SC-UTIME", func(t *testing.T) { checkSyscallRow(t, "UTIME", 132, actDeny) })
	t.Run("U-SC-UTIMES", func(t *testing.T) { checkSyscallRow(t, "UTIMES", 235, actDeny) })
	t.Run("U-SC-FUTIMESAT", func(t *testing.T) { checkSyscallRow(t, "FUTIMESAT", 261, actDeny) })
	t.Run("U-SC-UTIMENSAT", func(t *testing.T) { checkSyscallRow(t, "UTIMENSAT", 280, actDeny) })
	t.Run("U-SC-FILE_SETATTR", func(t *testing.T) { checkSyscallRow(t, "FILE_SETATTR", 469, actDeny) })
	t.Run("U-SC-MQ_OPEN", func(t *testing.T) { checkSyscallRow(t, "MQ_OPEN", 240, actDeny) })
	t.Run("U-SC-MQ_UNLINK", func(t *testing.T) { checkSyscallRow(t, "MQ_UNLINK", 241, actDeny) })
	t.Run("U-SC-MQ_TIMEDSEND", func(t *testing.T) { checkSyscallRow(t, "MQ_TIMEDSEND", 242, actDeny) })
	t.Run("U-SC-MQ_TIMEDRECEIVE", func(t *testing.T) { checkSyscallRow(t, "MQ_TIMEDRECEIVE", 243, actDeny) })
	t.Run("U-SC-MQ_NOTIFY", func(t *testing.T) { checkSyscallRow(t, "MQ_NOTIFY", 244, actDeny) })
	t.Run("U-SC-MQ_GETSETATTR", func(t *testing.T) { checkSyscallRow(t, "MQ_GETSETATTR", 245, actDeny) })
	t.Run("U-SC-SYNC", func(t *testing.T) { checkSyscallRow(t, "SYNC", 162, actDeny) })
	t.Run("U-SC-SYNCFS", func(t *testing.T) { checkSyscallRow(t, "SYNCFS", 306, actDeny) })
	t.Run("U-SC-CLONE3", func(t *testing.T) { checkSyscallRow(t, "CLONE3", 435, actEnosys) })
	t.Run("U-SC-USELIB", func(t *testing.T) { checkSyscallRow(t, "USELIB", 134, actEnosys) })
	t.Run("U-SC-_SYSCTL", func(t *testing.T) { checkSyscallRow(t, "_SYSCTL", 156, actEnosys) })
	t.Run("U-SC-CREATE_MODULE", func(t *testing.T) { checkSyscallRow(t, "CREATE_MODULE", 174, actEnosys) })
	t.Run("U-SC-GET_KERNEL_SYMS", func(t *testing.T) { checkSyscallRow(t, "GET_KERNEL_SYMS", 177, actEnosys) })
	t.Run("U-SC-QUERY_MODULE", func(t *testing.T) { checkSyscallRow(t, "QUERY_MODULE", 178, actEnosys) })
	t.Run("U-SC-NFSSERVCTL", func(t *testing.T) { checkSyscallRow(t, "NFSSERVCTL", 180, actEnosys) })
	t.Run("U-SC-GETPMSG", func(t *testing.T) { checkSyscallRow(t, "GETPMSG", 181, actEnosys) })
	t.Run("U-SC-PUTPMSG", func(t *testing.T) { checkSyscallRow(t, "PUTPMSG", 182, actEnosys) })
	t.Run("U-SC-AFS_SYSCALL", func(t *testing.T) { checkSyscallRow(t, "AFS_SYSCALL", 183, actEnosys) })
	t.Run("U-SC-TUXCALL", func(t *testing.T) { checkSyscallRow(t, "TUXCALL", 184, actEnosys) })
	t.Run("U-SC-SECURITY", func(t *testing.T) { checkSyscallRow(t, "SECURITY", 185, actEnosys) })
	t.Run("U-SC-LOOKUP_DCOOKIE", func(t *testing.T) { checkSyscallRow(t, "LOOKUP_DCOOKIE", 212, actEnosys) })
	t.Run("U-SC-EPOLL_CTL_OLD", func(t *testing.T) { checkSyscallRow(t, "EPOLL_CTL_OLD", 214, actEnosys) })
	t.Run("U-SC-EPOLL_WAIT_OLD", func(t *testing.T) { checkSyscallRow(t, "EPOLL_WAIT_OLD", 215, actEnosys) })
	t.Run("U-SC-VSERVER", func(t *testing.T) { checkSyscallRow(t, "VSERVER", 236, actEnosys) })
	t.Run("U-SC-CLONE", func(t *testing.T) { checkSyscallRow(t, "CLONE", 56, actDeny, 0x10000000) })
	t.Run("U-SC-UNSHARE", func(t *testing.T) { checkSyscallRow(t, "UNSHARE", 272, actDeny, 0x10000000) })
	t.Run("U-SC-SOCKET", func(t *testing.T) { checkSyscallRow(t, "SOCKET", 41, actDeny) })
	t.Run("U-SC-SOCKETPAIR", func(t *testing.T) { checkSyscallRow(t, "SOCKETPAIR", 53, actDeny) })
	t.Run("U-SC-IOCTL", func(t *testing.T) { checkSyscallRow(t, "IOCTL", 16, actDeny, 0, 0x5412) })
	t.Run("U-SC-FCNTL", func(t *testing.T) { checkSyscallRow(t, "FCNTL", 72, actDeny, 0, 1031) })
	t.Run("U-SC-FLOCK", func(t *testing.T) { checkSyscallRow(t, "FLOCK", 73, actDeny) })
	t.Run("U-SC-SETRLIMIT", func(t *testing.T) { checkSyscallRow(t, "SETRLIMIT", 160, actDeny, 4, 1) })
	t.Run("U-SC-PRLIMIT64", func(t *testing.T) { checkSyscallRow(t, "PRLIMIT64", 302, actDeny, 0, 4, 1) })
	t.Run("U-SC-PROCESS_MRELEASE", func(t *testing.T) { checkSyscallRow(t, "PROCESS_MRELEASE", 448, actDeny) })
	t.Run("U-SC-KILL", func(t *testing.T) { checkSyscallRow(t, "KILL", 62, actDeny, 1, 15) })
	t.Run("U-SC-TKILL", func(t *testing.T) { checkSyscallRow(t, "TKILL", 200, actDeny) })
	t.Run("U-SC-TGKILL", func(t *testing.T) { checkSyscallRow(t, "TGKILL", 234, actDeny) })
	t.Run("U-SC-RT_SIGQUEUEINFO", func(t *testing.T) { checkSyscallRow(t, "RT_SIGQUEUEINFO", 129, actDeny) })
	t.Run("U-SC-RT_TGSIGQUEUEINFO", func(t *testing.T) { checkSyscallRow(t, "RT_TGSIGQUEUEINFO", 297, actDeny) })
	t.Run("U-SC-PIDFD_SEND_SIGNAL", func(t *testing.T) { checkSyscallRow(t, "PIDFD_SEND_SIGNAL", 424, actDeny) })
	t.Run("U-SC-SETPRIORITY", func(t *testing.T) { checkSyscallRow(t, "SETPRIORITY", 141, actDeny, 2, 0) })
	t.Run("U-SC-IOPRIO_SET", func(t *testing.T) { checkSyscallRow(t, "IOPRIO_SET", 251, actDeny, 3, 0) })
	t.Run("U-SC-SCHED_SETPARAM", func(t *testing.T) { checkSyscallRow(t, "SCHED_SETPARAM", 142, actDeny, 1) })
	t.Run("U-SC-SCHED_SETSCHEDULER", func(t *testing.T) { checkSyscallRow(t, "SCHED_SETSCHEDULER", 144, actDeny, 1) })
	t.Run("U-SC-SCHED_SETAFFINITY", func(t *testing.T) { checkSyscallRow(t, "SCHED_SETAFFINITY", 203, actDeny, 1) })
	t.Run("U-SC-SCHED_SETATTR", func(t *testing.T) { checkSyscallRow(t, "SCHED_SETATTR", 314, actDeny, 1) })
	t.Run("U-SC-MIGRATE_PAGES", func(t *testing.T) { checkSyscallRow(t, "MIGRATE_PAGES", 256, actDeny, 1) })
	t.Run("U-SC-MOVE_PAGES", func(t *testing.T) { checkSyscallRow(t, "MOVE_PAGES", 279, actDeny, 1) })
}
